### ISSUE TITLE
Where is the code for Latent Image Guidance?

### ISSUE THREAD

**Issue by IDKiro** [XPixelGroup/DiffBIR#12]
I'm sorry to bother you again, as I have already started research based on your work.
I'm very interested in the Latent Image Guidance in Section 3.3, but I only found the classifier-free guidance strength in the inference code. I further found the relevant code in the sampler, but it seems like it's not enabled in the current version?

**Comment by 0x3f3f3f3fun** [comment]
We are glad to communicate with you once again! Latent Image Guidance is implemented in spaced_sampler.py and cond_fn.py. It's disabled in current version since we prefer higher quality rather than higher fidelity. We will enable it in inference.py and notify you as soon as possible. 😄

If you have any further questions, feel free to ask again.

**Comment by IDKiro** [comment]
Thank you for your quickly answer.
I'll try to do some experiments on cond_fn.

**Comment by 0x3f3f3f3fun** [comment]
Hello! We have uploaded the code.
