### ISSUE TITLE
request.txt

### ISSUE THREAD

**Issue by jcgfxk** [XPixelGroup/DiffBIR#24]
hello,when i install the diffbir, i meet with a problem

when i run "pip install -r requirements.txt", cmd shows "ERROR: Could not find a version that satisfies the requirement triton"

my already  used python is 3.11, i don't know if this is the cause of this problem

thank you for your time

![image](https://github.com/XPixelGroup/DiffBIR/assets/7160787/d91aa6be-e399-4a7b-b2e5-2ca734a582c8)

and what's more, when i input the "conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.3 -c pytorch", cmd shows as follow picture:
![image](https://github.com/XPixelGroup/DiffBIR/assets/7160787/7af84e3a-6660-4d2a-911a-ceb7932923ad)

sorry for my junior question

**Comment by 0x3f3f3f3fun** [comment]
Haha :), everyone has been frustrated due to environment configuration issues👻.
Refer to [this page](https://github.com/openai/triton/issues/1057), there are many reasons for this issue. Considering that your platform is Windows, I suggest two possible solutions:
- run `pip install https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl`
- upgrade pip and then run `pip install triton`

**Comment by jcgfxk** [comment]
thank you very much for your patience. Maybe my window11

**Comment by jcgfxk** [comment]
Thank you very much for your patience.
I try the method as https://github.com/openai/triton/issues/1057, unfortunately failed to resolve this issue
Maybe my window11 is not compatible, I will try it on Ubuntu
Thank you very much again

**Comment by CICSilver** [comment]
`pip install https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl` this need python>=3.10, I have tried this with py3.9 and got an error, then success with py3.10

**Comment by vincentkenny66** [comment]
![微信图片_20240223230158](https://github.com/XPixelGroup/DiffBIR/assets/125285049/8ba6f867-a03f-48ad-9171-864c654b0339)
Hello, I encountered this problem, how to deal with it?
