### ISSUE TITLE
 OpenXLab demo page not working

### ISSUE THREAD

**Issue by universewill** [XPixelGroup/DiffBIR#36]
rt

**Comment by 0x3f3f3f3fun** [comment]
Thanks for your feedback! We will fix it tomorrow.

**Comment by lucellent** [comment]
It's stuck in loading for me, I assume the issue is still there

**Comment by 0x3f3f3f3fun** [comment]
We made some updates last night and expect to be back online in 2 to 3 hours. Thanks for your interest! I will notify you when everything goes well. 😄

**Comment by 0x3f3f3f3fun** [comment]
The online demo is working! Please have a try!

**Comment by lucellent** [comment]
It works great, I assume tiles are meant to improve performance on larger images? It doesn't do that well, the tiles are very obvious

<img width="136" alt="Screenshot_198" src="https://github.com/XPixelGroup/DiffBIR/assets/38135928/5812f17d-4b3f-40ae-b161-04b2e07ade78">
<img width="618" alt="Screenshot_199" src="https://github.com/XPixelGroup/DiffBIR/assets/38135928/8bab6fab-7509-4489-b33c-f78eefe7d4a3">

**Comment by lucellent** [comment]
Not working again :(

**Comment by 0x3f3f3f3fun** [comment]
> It works great, I assume tiles are meant to improve performance on larger images? It doesn't do that well, the tiles are very obvious
> 
> <img alt="Screenshot_198" width="136" src="https://user-images.githubusercontent.com/38135928/268439219-5812f17d-4b3f-40ae-b161-04b2e07ade78.png"> <img alt="Screenshot_199" width="618" src="https://user-images.githubusercontent.com/38135928/268439222-8bab6fab-7509-4489-b33c-f78eefe7d4a3.png">

Sorry, I haven't respond to your question in a timely manner. I've also encountered this issue while using tiled sampling. I guess the problem is that the image content of the patch are too far from the distribution of natural images, resulting in a high degree of randomness in the generation of DiffBIR, leading to differences between these patches. We should notice that:
1. When using the tile mode, try to make the content of the images in the patch as close to natural images as possible.
2. DiffBIR is not designed for large-scale super-resolution, it's a image restoration model, so it's better to keep the output size around a resolution of 2000. Thank you for your interest in DiffBIR!

**Comment by 0x3f3f3f3fun** [comment]
> Not working again :(

Sorry, I haven't modified the code but the app can not  reboot. And I can not find any log about the problem, I will try to fix it as soon as possible!

**Comment by lucellent** [comment]
We appreciate you working so hard on this!

Is it possible in the future this would work as a general upscaler? Because for that it's so good, the limit right now is the output resolution, it can't handle bigger images well
