### ISSUE TITLE
Is torchtext  mandatory？

### ISSUE THREAD

**Issue by zdyshine** [XPixelGroup/DiffBIR#5]

**Comment by zdyshine** [comment]
> _No description provided._

Thanks for the reply!
There is torchtext in my local environment. When using DiffBIR and adapting to the inference environment, I found that pytorch_lightning has a dependency on torchtext, /opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py. You can also run the code without torchtext installed. I uninstalled torchtext, and finally used the provided sample code to successfully run the results, but the quality of the recovered images was very poor, and I don't know why.
<img width="756" alt="DIffBIR_github" src="https://github.com/XPixelGroup/DiffBIR/assets/35593072/396b3386-403b-4be7-9bf9-ade66990dc65">

**Comment by 0x3f3f3f3fun** [comment]
This issue is unrelated to torchtext. Your result is reasonable and falls under DiffBIR's bad cases. Currently, the stage1 model produces over-smoothed results, causing details like text and small faces to be erased in the first stage, making it impossible for the second stage to perform generation. Additionally, the image you've shown appears to be from a low-resolution video with video compression artifacts. In our experiments, we have also observed that DiffBIR tends to generate some noisy textures when dealing with such compression noise. These are known issues with DiffBIR at the moment, and we are actively working on improvements to enhance its performance. Thank you for bringing this issue to our attention!

**Comment by 0x3f3f3f3fun** [comment]
You can improve DiffBIR's performance by tuning inference parameters, such as:
- set `sr_scale` to a value larger than 1 to alleviate the "over-smoothed" problem.
- set `prompt guidance scale` to a value larger than 1 to enable the negative prompt, which can reduce bad cases and improve the image quality.

Due to the stochastic nature of the diffusion model, you can also change the random seed to select a good result for yourself (we will never perform this action in our experiments!).

We hope these suggestions are helpful for you. Here are two examples with video compression artifacts:
<img width="596" alt="diffbir_example2" src="https://github.com/XPixelGroup/DiffBIR/assets/71883756/6134ba4b-bef6-49a0-af36-aa20c89526b7">
<img width="613" alt="diffbir_example3" src="https://github.com/XPixelGroup/DiffBIR/assets/71883756/c95170ed-50a0-4adc-8f5a-3a9a333d2309">

**Comment by zdyshine** [comment]
> You can improve DiffBIR's performance by tuning inference parameters, such as:
> 
> * set `sr_scale` to a value larger than 1 to alleviate the "over-smoothed" problem.
> * set `prompt guidance scale` to a value larger than 1 to enable the negative prompt, which can reduce bad cases and improve the image quality.
> 
> Due to the stochastic nature of the diffusion model, you can also change the random seed to select a good result for yourself (we will never perform this action in our experiments!).
> 
> We hope these suggestions are helpful for you. Here are two examples with video compression artifacts: <img alt="diffbir_example2" width="596" src="https://user-images.githubusercontent.com/71883756/265727073-6134ba4b-bef6-49a0-af36-aa20c89526b7.png"> <img alt="diffbir_example3" width="613" src="https://user-images.githubusercontent.com/71883756/265727157-c95170ed-50a0-4adc-8f5a-3a9a333d2309.png">

Thanks for the reply, I will try to adjust the parameters

**Comment by zdyshine** [comment]
When I installed xformers==0.0.16, it prompted that torch requires 1.13. Have you encountered such a problem?
<img width="842" alt="DIffBIR_github" src="https://github.com/XPixelGroup/DiffBIR/assets/35593072/0322ff9e-571f-4f7d-b647-fcd433ab8063">

**Comment by 0x3f3f3f3fun** [comment]
Yes, I've encountered this problem as well. [xformers](https://github.com/facebookresearch/xformers) has strict requirements for both PyTorch and CUDA versions. I recommend you to create a separate environment as shown in the README.md and then install the PyTorch version that matches with xformers.
